name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 0
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_stargazers: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>100 
          plugin_notable_self: yes
          plugin_gists: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 9943464
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_KEY }}
          plugin_wakatime_user: ewen-lbh
          plugin_rss: yes
          plugin_rss_source: https://ewen.works/blog/rss.xml
          
